import {StyleSheet} from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    padding: 20,
    backgroundColor: '#FFFFFF',
  },
  labelText: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#000000',
    marginBottom: 10,
  },
  helperText: {
    fontSize: 14,
    color: '#2527BF',
    marginBottom: 20,
  },
  addressContainer: {
    marginBottom: 30,
  },
  addressInput: {
    height: 50,
    backgroundColor: '#F6F6F6',
    borderRadius: 10,
    padding: 10,
    fontSize: 16,
    color: '#000000',
    marginBottom: 10,
  },
  detailedAddressInput: {
    height: 50,
    backgroundColor: '#F6F6F6',
    borderRadius: 10,
    padding: 10,
    fontSize: 16,
    color: '#000000',
    marginBottom: 10,
  },
  deleteButton: {
    position: 'absolute',
    top: -5,
    right: -5,
    backgroundColor: '#2527BF',
    borderRadius: 50,
    padding: 6,
    width: 30,
    height: 30,
    justifyContent: 'center',
    alignItems: 'center',
  },
  deleteButtonText: {
    color: '#FFFFFF',
    fontWeight: 'bold',
    fontSize: 15,
    top: -2,
  },
  additionalInfoContainer: {
    marginBottom: 20,
  },
  textInput: {
    height: 150,
    backgroundColor: '#F6F6F6',
    borderRadius: 10,
    padding: 10,
    fontSize: 16,
    color: '#000000',
    textAlignVertical: 'top',
  },
  characterCount: {
    textAlign: 'right',
    color: '#B5B5B5',
  },
  submitButton: {
    position: 'absolute',
    bottom: 30,
    left: 16,
    right: 16,
    height: 50,
    backgroundColor: '#2527BF',
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  submitButtonText: {
    fontSize: 18,
    color: '#FFFFFF',
    fontWeight: 'bold',
  },
  inputWithIconAndCounterContainer: {
    position: 'relative',
    backgroundColor: '#F6F6F6',
    borderRadius: 10,
  },
  textInputWithIconAndCounter: {
    height: 200,
    padding: 10,
    paddingLeft: 15,
    paddingBottom: 30,
    fontSize: 16,
    color: '#000000',
    textAlignVertical: 'top',
  },
  microphoneIconInside: {
    position: 'absolute',
    left: 10,
    top: 140,
    width: 40,
    height: 40,
  },
  characterCountInside: {
    position: 'absolute',
    right: 10,
    bottom: 10,
    fontSize: 16,
    color: '#B5B5B5',
  },
});

export default styles;
